name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use actions/setup-elixir
        id: setup-elixir
        uses: ./
        with:
          otp-version: '24.x'
          elixir-version:  '1.12.x'
      - name: Output runtime versions
        run: echo "Elixir ${{steps.setup-elixir.outputs.elixir-version}} / OTP ${{steps.setup-elixir.outputs.otp-version}}"
      - name: Run Mix project tests
        run: |-
          cd elixir
          mix deps.get
          mix test

#       - name: Set up Elixir
#         uses: actions/setup-elixir@v1
#         with:
#           elixir-version: '1.12.x'
#           otp-version: '24.x'

#       - name: Install dependencies
#         run: mix deps.get

#       - name: Run tests
#         run: mix test
