name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '25'
        elixir-version: '1.14.5'

    - name: Build and test
      run: |
        mix deps.get
        mix compile
        mix test || (mkdir -p screenshots/failure && touch screenshots/failure/failure.txt && exit 1)
        mkdir -p screenshots/success && touch screenshots/success/success.txt
    - name: Store screenshots for failure
      uses: actions/upload-artifact@v2
      with:
          name: failure-screenshots
          path: screenshots/failure

      if: ${{ failure() }}

    - name: Store screenshots for success
      uses: actions/upload-artifact@v2
      with:
          name: success-screenshots
          path: screenshots/success

      if: ${{ success() }}
